### ISSUE TITLE
网址打不开

### ISSUE THREAD

**Issue by floxy** [haisheng2017/yys-optimizer#1]
添加了代理还是打不开

**Comment by haisheng2017** [comment]
你好
我这里手机和电脑都可以正常使用。请确认打不开的错误信息，如连接错误、找不到资源等等。
另外请务必使用https。
如页面白屏无加载动作等，请确认浏览器内核为IE9及以上。
如页面无资源请求，请确认浏览器是否开启JS屏蔽等。

**Comment by floxy** [comment]
> 你好 我这里手机和电脑都可以正常使用。请确认打不开的错误信息，如连接错误、找不到资源等等。 另外请务必使用https。 如页面白屏无加载动作等，请确认浏览器内核为IE9及以上。 如页面无资源请求，请确认浏览器是否开启JS屏蔽等。
